main: ru.velialcult.library.CultLibrary
api-version: 1.16
version: '${project.version}'
name: CultLibrary
website: https://vk.com/velialcultstudio
author: Nilsson03
softdepend:
  - PlaceholderAPI
  - ProtocolLib
  - Vault