main: ru.velialcult.library.CultLibrary
api-version: 1.16
version: '${project.version}'
name: CultLibrary
author: https://leaked-minecraft.pro/velialcult/
softdepend:
  - PlaceholderAPI
  - ProtocolLib
  - Vault